language: elixir
sudo:     false

jobs:
  include:
    - &test
      stage:         test
      elixir:        1.2.6
      otp_release:   18.3
      env:           MIX_ENV=test
      after_success: mix coveralls.travis
    - <<: *test
      elixir:        1.3.4
      after_success: true
    - <<: *test
      elixir:        1.4.5
      after_success: true
    - <<: *test
      elixir:        1.5.1
      after_success: true
    - <<: *test
      elixir:        1.5.1
      otp_release:   19.3
      after_success: true
    - <<: *test
      elixir:        1.5.1
      otp_release:   20.0
      after_success: true
    - stage:       verify
      elixir:      1.2.6
      otp_release: 18.3
      env:         MIX_ENV=prod
      script: |-
        cd "${TRAVIS_BUILD_DIR}/verify"
        mix compile
        mix ua_inspector.verify
