language: elixir

env:
  - MIX_ENV=test TEST_ENV=ex_unit
  - MIX_ENV=prod TEST_ENV=verify

script:        . ${TRAVIS_BUILD_DIR}/travis/${TEST_ENV}_script.sh
after_success: . ${TRAVIS_BUILD_DIR}/travis/${TEST_ENV}_after_success.sh
